Understand how individual item prices evolve over time during a league and identify patterns such as volatility, stability, and early-league price spikes.

## Importing libraries

In [9]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from itables import show

## Importing data

In [18]:
items_processed = pd.read_csv("C:/Users/user/Desktop/Data Science/PoeMarketAnalyser/data/poeninja/items_data_processed/high_conf_items_processed_day.csv", sep=";", low_memory=False)

# Item Price Dynamics

### Daily price changes of an item during a league

In [19]:
item_time_series = (items_processed.groupby(["League", "Name", "Day"])["Value"].median().reset_index())
show(item_time_series)

### Average price of each item across the leagues

In [20]:
mean_price_per_item = (item_time_series.groupby(["League", "Name"])["Value"].mean().reset_index(name="mean_price"))
mean_price_per_item

           League                               Name  mean_price
0      Affliction  +1% Chance to Block Attack Damage    3.473624
1      Affliction           +12% to Chaos Resistance    8.633091
2      Affliction            +15% to Cold Resistance    2.574045
3      Affliction            +15% to Fire Resistance    3.526136
4      Affliction       +15% to Lightning Resistance    2.776386
...           ...                                ...         ...
28635    Settlers                   Zeel's Amplifier    1.000000
28636    Settlers                     Zerphi's Heart  552.076894
28637    Settlers               Zerphi's Last Breath    7.358994
28638    Settlers                       Ziggurat Map   86.819748
28639    Settlers                     Zodiac Leather    8.979151

[28640 rows x 3 columns]

In [23]:
mean_price_per_item.sort_values("mean_price",ascending=False).head(10)

            League                        Name     mean_price
18434  Mercenaries                Original Sin  209103.954812
16353  Mercenaries  Awakened Enlighten Support  207124.053011
2209    Affliction                Original Sin  191305.444794
26803     Settlers                Original Sin  174735.985382
20645   Necropolis  Awakened Enlighten Support  139515.313600
16351  Mercenaries    Awakened Empower Support  137582.176163
3333    Affliction      The Original Scripture  136725.432337
19679  Mercenaries      The Original Scripture  132508.652836
22656   Necropolis                Original Sin  112443.537035
13690      Keepers                Original Sin   99322.158347

### Items segmentation

In [25]:
mean_price_per_item["price_segment"] = pd.qcut(mean_price_per_item["mean_price"],q=3,labels=["cheap", "mid-range", "expensive"])
mean_price_per_item["price_segment"].value_counts()

price_segment
cheap        9547
expensive    9547
mid-range    9546
Name: count, dtype: int64

In [26]:
mean_price_per_item.sort_values("mean_price").head(10)

           League            Name  mean_price price_segment
12150     Keepers         Fencoil    0.080697         cheap
5908     Ancestor       Clear Oil    0.090917         cheap
8783     Ancestor       Sepia Oil    0.092431         cheap
21194  Necropolis       Clear Oil    0.093103         cheap
23170  Necropolis       Sepia Oil    0.102845         cheap
12941     Keepers  Hrimnor's Hymn    0.105000         cheap
2747   Affliction       Sepia Oil    0.106743         cheap
792    Affliction       Clear Oil    0.107615         cheap
20483  Necropolis       Amber Oil    0.121681         cheap
14278     Keepers    Saemus' Gift    0.121748         cheap

In [27]:
mean_price_per_item.sort_values("mean_price").tail(10)

            League                        Name     mean_price price_segment
13690      Keepers                Original Sin   99322.158347     expensive
22656   Necropolis                Original Sin  112443.537035     expensive
19679  Mercenaries      The Original Scripture  132508.652836     expensive
3333    Affliction      The Original Scripture  136725.432337     expensive
16351  Mercenaries    Awakened Empower Support  137582.176163     expensive
20645   Necropolis  Awakened Enlighten Support  139515.313600     expensive
26803     Settlers                Original Sin  174735.985382     expensive
2209    Affliction                Original Sin  191305.444794     expensive
16353  Mercenaries  Awakened Enlighten Support  207124.053011     expensive
18434  Mercenaries                Original Sin  209103.954812     expensive